// Translate text nodes in place so icons, form values, and event listeners survive.
const bangla = {
  'Home':'হোম','Why WOLT':'কেন WOLT','The program':'প্রোগ্রাম','Career tracks':'ক্যারিয়ার ট্র্যাক','Your growth':'আপনার অগ্রগতি','Apply now':'আবেদন করুন',
  'BIG AMBITIONS. REAL OPPORTUNITIES.':'বড় স্বপ্ন। বাস্তব সুযোগ।','Build skills.':'দক্ষতা গড়ুন।','Find your stride.':'আত্মবিশ্বাস বাড়ান।','Start your career.':'ক্যারিয়ার শুরু করুন।',
  'Your degree is just the beginning. Turn your potential into real workplace experience with a guided, 3-month internship at WOLT.':'আপনার ডিগ্রি কেবল শুরু। WOLT-এর তিন মাসের ইন্টার্নশিপে সঠিক দিকনির্দেশনার সঙ্গে নিজের সম্ভাবনাকে বাস্তব কাজের অভিজ্ঞতায় রূপ দিন।',
  'Find your opportunity':'আপনার সুযোগ খুঁজুন','Explore the program':'প্রোগ্রাম সম্পর্কে জানুন','Made for fresh graduates.':'সদ্য স্নাতকদের জন্য।','Built for your next big step.':'আপনার পরবর্তী পদক্ষেপের প্রস্তুতি।','3 months':'৩ মাস','A world of possibilities':'সম্ভাবনার নতুন দিগন্ত',
  'YOUR FUTURE, IN GOOD COMPANY':'সঠিক সঙ্গেই গড়ুন আপনার ভবিষ্যৎ','Real work. Real growth.':'বাস্তব কাজ। সত্যিকারের অগ্রগতি।','Learn by doing, every day.':'প্রতিদিন কাজের মাধ্যমে শিখুন।','From potential to professional':'সম্ভাবনা থেকে পেশাদারিত্বে','One confident step at a time.':'প্রতিটি পদক্ষেপে আত্মবিশ্বাস।','01 / YOUR NEXT CHAPTER':'০১ / আপনার নতুন অধ্যায়',
  '01 / WHY WOLT':'০১ / কেন WOLT','A little guidance.':'একটু দিকনির্দেশনা।','A':'আনে','big difference.':'বড় পরিবর্তন।',
  "The space between graduation and your first job can feel big. We're here to help you cross it.":'স্নাতক শেষ করা থেকে প্রথম চাকরি—পথটা কঠিন মনে হতে পারে। এই পথ পাড়ি দিতে আমরা আপনার পাশে আছি।',
  'THE STARTING POINT':'শুরুর চ্যালেঞ্জ','Sound familiar?':'আপনারও কি এমন মনে হয়?','Limited workplace exposure':'কর্মক্ষেত্রের অভিজ্ঞতা কম','Gaps between theory and practice':'তত্ত্ব ও বাস্তব কাজের মধ্যে ব্যবধান','Low professional confidence':'পেশাগত আত্মবিশ্বাসের অভাব','Unsure how to take the next step':'পরবর্তী পদক্ষেপ নিয়ে অনিশ্চয়তা','THE WOLT WAY':'WOLT-এর পথ',"Let's move you forward.":'চলুন, এগিয়ে যাই।','Real responsibilities from the start':'শুরু থেকেই বাস্তব দায়িত্ব','Hands-on training and mentoring':'হাতে-কলমে প্রশিক্ষণ ও মেন্টরিং','Support to become workplace-ready':'কর্মক্ষেত্রের জন্য প্রস্তুত হওয়ার সহায়তা','A performance-based career pathway':'কাজের মূল্যায়নভিত্তিক ক্যারিয়ারের পথ',
  '02 / THE PROGRAM':'০২ / প্রোগ্রাম','Three months.':'তিন মাস।','A stronger beginning.':'আরও দৃঢ় সূচনা।','Join a relevant department, take on meaningful responsibilities, and grow with people who guide you along the way.':'উপযুক্ত বিভাগে যোগ দিন, বাস্তব দায়িত্ব নিন এবং অভিজ্ঞদের দিকনির্দেশনায় নিজেকে গড়ে তুলুন।','Make your next move':'পরের পদক্ষেপ নিন','THE DURATION':'সময়কাল',"WHO IT'S FOR":'যাদের জন্য','University graduates':'বিশ্ববিদ্যালয়ের স্নাতক','YOUR COMMITMENT':'আপনার অঙ্গীকার','The full journey':'সম্পূর্ণ প্রোগ্রামে অংশগ্রহণ','MONTHLY ALLOWANCE':'মাসিক ভাতা','BDT 5,000–10,000':'৫,০০০–১০,০০০ টাকা','Bring your curiosity, commitment, and a mindset ready to grow.':'সঙ্গে আনুন কৌতূহল, নিষ্ঠা এবং শেখার আগ্রহ।',
  '03 / FIND YOUR DIRECTION':'০৩ / নিজের পথ খুঁজুন','Different strengths.':'প্রতিভা সবার আলাদা।','Your kind of track.':'বেছে নিন নিজের ট্র্যাক।','Find a place to put your potential to work. Roles depend on your academic background and organizational needs.':'নিজের সম্ভাবনা কাজে লাগানোর সুযোগ খুঁজুন। আপনার শিক্ষাগত পটভূমি ও প্রতিষ্ঠানের প্রয়োজন অনুযায়ী দায়িত্ব নির্ধারিত হবে।',
  'Web Development':'ওয়েব ডেভেলপমেন্ট','Software / IT':'সফটওয়্যার / আইটি','Digital Marketing':'ডিজিটাল মার্কেটিং','Business Development':'বিজনেস ডেভেলপমেন্ট','HR / Administration':'মানবসম্পদ / প্রশাসন','Communication':'যোগাযোগ',
  'Bring ideas to life with frontend development, websites, and UI implementation.':'ফ্রন্টএন্ড ডেভেলপমেন্ট, ওয়েবসাইট ও ইউআই তৈরির মাধ্যমে ধারণাকে বাস্তবে রূপ দিন।','BUILD SOMETHING GREAT':'দারুণ কিছু তৈরি করুন','Explore technical support, systems, and the digital operations behind a business.':'টেকনিক্যাল সাপোর্ট, সিস্টেম এবং ব্যবসার ডিজিটাল কার্যক্রম সম্পর্কে শিখুন।','MAKE THINGS WORK':'প্রযুক্তিকে কাজে লাগান','Connect brands and people through content, campaigns, social platforms, and analytics.':'কনটেন্ট, ক্যাম্পেইন, সামাজিক মাধ্যম ও অ্যানালিটিক্সের মাধ্যমে ব্র্যান্ড ও মানুষের সংযোগ গড়ুন।','MAKE AN IMPACT':'ইতিবাচক প্রভাব রাখুন','Discover opportunities through outreach, client communication, and business support.':'আউটরিচ, ক্লায়েন্টের সঙ্গে যোগাযোগ ও ব্যবসায়িক সহায়তার মাধ্যমে নতুন সুযোগ খুঁজুন।','GROW NEW POSSIBILITIES':'নতুন সম্ভাবনা গড়ুন','Support the people behind the work with recruitment, documentation, and coordination.':'নিয়োগ, নথিপত্র তৈরি ও সমন্বয়ের মাধ্যমে প্রতিষ্ঠানের কর্মীদের সহায়তা করুন।','PUT PEOPLE FIRST':'মানুষকে প্রাধান্য দিন','Find your professional voice through thoughtful content, communication, and coordination.':'কনটেন্ট, যোগাযোগ ও সমন্বয়ের মাধ্যমে পেশাগতভাবে নিজেকে প্রকাশ করতে শিখুন।','START A CONVERSATION':'যোগাযোগের শুরু হোক',
  '04 / MORE THAN EXPERIENCE':'০৪ / অভিজ্ঞতার বাইরেও','Skills for work.':'কাজের জন্য দক্ষতা।','Confidence':'আত্মবিশ্বাস','for life.':'জীবনের জন্য।','Your next chapter takes more than technical knowledge. Build the everyday skills that help you show up, speak up, and move forward.':'আপনার পরবর্তী অধ্যায়ের জন্য প্রযুক্তিগত জ্ঞানের পাশাপাশি আরও কিছু দরকার। দৈনন্দিন দক্ষতা গড়ুন, যা আপনাকে অংশ নিতে, নিজের কথা বলতে ও এগিয়ে যেতে সাহায্য করবে।','Better together. Stronger tomorrow. ↗':'একসঙ্গে শিখি। আরও দৃঢ় ভবিষ্যৎ গড়ি। ↗',
  'In-house training':'প্রতিষ্ঠানের নিজস্ব প্রশিক্ষণ','Practical skills for real workplace situations.':'কর্মক্ষেত্রের বাস্তব পরিস্থিতির জন্য প্রয়োজনীয় দক্ষতা।','Professional mentoring':'পেশাগত মেন্টরিং','Guidance, feedback, and accountability.':'দিকনির্দেশনা, গঠনমূলক পরামর্শ ও দায়িত্ববোধ।','CV & cover letter support':'সিভি ও কভার লেটারে সহায়তা','Tell your story with clarity and confidence.':'নিজের অভিজ্ঞতা স্পষ্টভাবে ও আত্মবিশ্বাসের সঙ্গে তুলে ধরুন।','Professional communication':'পেশাগত যোগাযোগ','Email, teamwork, and workplace etiquette.':'ইমেইল, দলগত কাজ ও কর্মক্ষেত্রের শিষ্টাচার।','English speaking':'ইংরেজিতে কথা বলা','Find confidence in professional conversations.':'পেশাগত কথোপকথনে আত্মবিশ্বাস বাড়ান।','Job application guidance':'চাকরির আবেদনে দিকনির্দেশনা','Prepare for applications and interviews.':'আবেদন ও সাক্ষাৎকারের প্রস্তুতি নিন।',
  '05 / THE ROAD AHEAD':'০৫ / সামনের পথ','Small steps.':'ছোট ছোট পদক্ষেপ।','Meaningful progress.':'অর্থবহ অগ্রগতি।','From your first application to your next opportunity, every step is a chance to grow.':'প্রথম আবেদন থেকে পরবর্তী সুযোগ—প্রতিটি ধাপেই নিজেকে গড়ে তোলার সম্ভাবনা।','Apply':'আবেদন','Shortlist':'প্রাথমিক বাছাই','Interview':'সাক্ষাৎকার','Department':'বিভাগ','Real work':'বাস্তব কাজ','Mentoring':'মেন্টরিং','KPI review':'কেপিআই মূল্যায়ন','Placement':'চাকরির সুযোগ','HOW YOU GROW':'যেভাবে এগিয়ে যাবেন','Progress that matters.':'যে অগ্রগতি গুরুত্বপূর্ণ।','Our performance evaluation looks at:':'কাজের মূল্যায়নে আমরা বিবেচনা করি:','Attendance & discipline':'উপস্থিতি ও শৃঙ্খলা','Task completion':'কাজ সম্পন্ন করা','Professional behavior':'পেশাগত আচরণ','Communication & teamwork':'যোগাযোগ ও দলগত কাজ','Learning progress':'শেখার অগ্রগতি','YOUR NEXT OPPORTUNITY':'আপনার পরবর্তী সুযোগ','A beginning with possibilities.':'সম্ভাবনাময় একটি সূচনা।','Successful interns may receive placement opportunities based on KPI evaluation, performance, and available openings.':'সফল ইন্টার্নরা কেপিআই মূল্যায়ন, কাজের মান ও শূন্যপদ অনুযায়ী চাকরির সুযোগ পেতে পারেন।','Placement is an opportunity, not a guaranteed outcome.':'চাকরির সুযোগ থাকতে পারে, তবে চাকরি নিশ্চিত নয়।',
  "06 / LET'S BEGIN":'০৬ / চলুন শুরু করি','Your next chapter':'আপনার নতুন অধ্যায়','starts with you.':'শুরু হোক আপনাকে দিয়ে।',"Bring your ambition. We'll help you take the first step toward professional life.":'আপনার স্বপ্ন নিয়ে এগিয়ে আসুন। পেশাজীবনের প্রথম পদক্ষেপে আমরা পাশে থাকব।','A few things to have ready':'যা প্রস্তুত রাখবেন','An updated CV / resume':'হালনাগাদ সিভি / জীবনবৃত্তান্ত','A recent photograph':'সাম্প্রতিক ছবি','A cover letter or short introduction':'কভার লেটার বা সংক্ষিপ্ত পরিচিতি','GROW INTO':'বিকশিত করুন','YOUR POTENTIAL.':'নিজের সম্ভাবনা।','YOUR FUTURE STARTS HERE':'আপনার ভবিষ্যতের শুরু এখানেই','Apply to WOLT':'WOLT-এ আবেদন করুন','Tell us a little about yourself.':'নিজের সম্পর্কে কিছু তথ্য দিন।',
  'Full name':'পুরো নাম','Your full name':'আপনার পুরো নাম','Email address':'ইমেইল ঠিকানা','Phone number':'ফোন নম্বর','Your phone number':'আপনার ফোন নম্বর','University':'বিশ্ববিদ্যালয়','Your university':'আপনার বিশ্ববিদ্যালয়','Preferred track':'পছন্দের ট্র্যাক','Choose your track':'ট্র্যাক বেছে নিন','Graduation year':'স্নাতক পাসের বছর','e.g. 2026':'যেমন: 2026','CV / Resume':'সিভি / জীবনবৃত্তান্ত','PDF, DOC or DOCX · Max 5 MB':'PDF, DOC বা DOCX · সর্বোচ্চ ৫ মেগাবাইট','Recent photograph':'সাম্প্রতিক ছবি','JPG or PNG · Max 5 MB':'JPG বা PNG · সর্বোচ্চ ৫ মেগাবাইট','Cover letter / short introduction':'কভার লেটার / সংক্ষিপ্ত পরিচিতি','What excites you about this opportunity?':'এই সুযোগের কোন বিষয়টি আপনাকে আগ্রহী করেছে?','Frontend preview — your information and files will not be sent or saved.':'ফ্রন্টএন্ড প্রিভিউ — আপনার তথ্য ও ফাইল পাঠানো বা সংরক্ষণ করা হবে না।','Preview application':'আবেদনের প্রিভিউ দেখুন','Real experience. Lasting confidence.':'বাস্তব অভিজ্ঞতা। স্থায়ী আত্মবিশ্বাস।',
  'APPLICATION PREVIEW':'আবেদনের প্রিভিউ','Looking good,':'চমৎকার,','Your details are ready for the':'আপনার তথ্য প্রস্তুত। পছন্দের ট্র্যাক:','track.':'।','This is a frontend demo. No application has been submitted, and no files or personal information have been uploaded.':'এটি একটি ফ্রন্টএন্ড ডেমো। কোনো আবেদন জমা দেওয়া হয়নি এবং কোনো ফাইল বা ব্যক্তিগত তথ্য আপলোড করা হয়নি।','Back to application ↗':'আবেদনে ফিরে যান ↗','Preview ready. Nothing has been submitted.':'প্রিভিউ প্রস্তুত। কিছু জমা দেওয়া হয়নি।',
  'Please choose a file smaller than 5 MB.':'৫ মেগাবাইটের চেয়ে ছোট ফাইল বেছে নিন।','Please choose a supported file type.':'অনুমোদিত ধরনের ফাইল বেছে নিন।','Switch to dark mode':'ডার্ক মোড চালু করুন','Switch to light mode':'লাইট মোড চালু করুন','Switch color theme':'রঙের থিম বদলান','Open navigation':'মেনু খুলুন','Close navigation':'মেনু বন্ধ করুন','Main navigation':'মূল মেনু','WOLT home':'WOLT হোম','Back to top':'উপরে ফিরুন','Close preview':'প্রিভিউ বন্ধ করুন','A confident graduate holding a laptop in a bright modern office':'উজ্জ্বল আধুনিক অফিসে ল্যাপটপ হাতে আত্মবিশ্বাসী একজন স্নাতক','A team collaborating around a laptop':'ল্যাপটপ ঘিরে দলগত কাজ',
  'WOLT — Your next chapter starts here':'WOLT — আপনার নতুন অধ্যায়ের শুরু এখানেই','Build practical skills and start your professional journey with the WOLT three-month internship program.':'WOLT-এর তিন মাসের ইন্টার্নশিপে বাস্তব দক্ষতা গড়ুন এবং পেশাজীবন শুরু করুন।'
};
let currentLanguage = 'en';
try { if (localStorage.getItem('wolt-language') === 'bn') currentLanguage = 'bn'; } catch {}
function translate(text) { return currentLanguage === 'bn' ? (bangla[text] ?? text) : text; }
// Explicit option values remain English so language changes never change selections.
document.querySelectorAll('#track-select option').forEach(option => {
  if (!option.hasAttribute('value')) option.value = option.textContent;
});
const translatedNodes = [];
const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
while (walker.nextNode()) {
  const node = walker.currentNode;
  if (node.parentElement.closest('script, style, .language-toggle')) continue;
  const key = node.textContent.trim();
  if (Object.hasOwn(bangla, key)) translatedNodes.push({node, original:node.textContent, key});
}
const translatedAttributes = [];
document.querySelectorAll('[placeholder], [aria-label], [title], meta[name="description"]').forEach(element => {
  for (const attribute of ['placeholder','aria-label','title','content']) {
    const original = element.getAttribute(attribute);
    if (original && Object.hasOwn(bangla, original)) translatedAttributes.push({element,attribute,original});
  }
});
const englishTitle = document.title;
function setLanguage(language) {
  currentLanguage = language === 'bn' ? 'bn' : 'en';
  document.documentElement.lang = currentLanguage;
  translatedNodes.forEach(({node, original, key}) => { node.textContent = original.replace(key, translate(key)); });
  translatedAttributes.forEach(({element,attribute,original}) => element.setAttribute(attribute, translate(original)));
  document.title = translate(englishTitle);
  const button = document.querySelector('.language-toggle');
  button.querySelector('[data-language="en"]').classList.toggle('selected', currentLanguage === 'en');
  button.querySelector('[data-language="bn"]').classList.toggle('selected', currentLanguage === 'bn');
  button.setAttribute('aria-label', currentLanguage === 'bn' ? 'Switch to English' : 'বাংলায় দেখুন');
  button.setAttribute('aria-pressed', String(currentLanguage === 'bn'));
  document.dispatchEvent(new Event('languagechange'));
}
document.querySelector('.language-toggle').addEventListener('click', () => {
  setLanguage(currentLanguage === 'en' ? 'bn' : 'en');
  try { localStorage.setItem('wolt-language', currentLanguage); } catch {}
});
setLanguage(currentLanguage);
